# Generated by Django 3.0.8 on 2020-07-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorfirstName', models.CharField(default='', max_length=100)),
                ('authorlastName', models.CharField(default='', max_length=100)),
                ('authorBio', models.CharField(default='', max_length=1000)),
                ('publisher', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BookRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookRating', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('genre', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('publisher', models.CharField(default='', max_length=1000)),
                ('bookISBN', models.CharField(default='', max_length=100, unique=True)),
                ('yearPublished', models.CharField(default='', max_length=5)),
                ('copiesSold', models.CharField(default='', max_length=100000000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookAuthor', to='bookdetails.BookAuthor')),
            ],
        ),
    ]
