# Generated by Django 3.0.8 on 2020-07-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='card_cvc',
            new_name='card_ccv',
        ),
    ]
