# Generated by Django 3.0.8 on 2020-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200728_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_ccv',
            field=models.CharField(default='', max_length=5),
        ),
    ]
